name: brambldart
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  pointycastle: ^3.1.3
  collection: ^1.15.0
  convert: ^3.0.1
  uuid: ^3.0.4
  unorm_dart: ^0.2.0
  intl: ^0.17.0
  http: ^0.13.3
  json_annotation: ^4.1.0
  dio: ^4.0.0
  meta: ^1.7.0
  bip_topl: ^0.0.1
  pinenacl: ^0.3.3
  docker_process: ^1.3.0
  logging: ^1.0.2

