name: mubrambl
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  pointycastle: ^3.1.3
  collection: ^1.15.0
  fast_base58: ^0.2.0
  bip39: ^1.0.6
  logging: ^1.0.1
  bip32_ed25519: ^0.2.1
  crypto: ^3.0.1
  cryptography: ^2.0.2
  convert: ^3.0.1
  uuid: ^3.0.4
  hex: ^0.2.0
  ed25519_edwards: ^0.2.1
  built_collection: ^5.1.0

